version: '3.8'
services:
  backend:
    build: .
    container_name: MedShareNetwork-Production
    # depends_on:
    #   - database
    ports:
      - '1000:1000'
    environment:
      - SECRET_KEY=${SECRET_KEY} # Example of passing environment variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  # database:
  #   image: mysql:latest
  #   container_name: MedShareNetwork-Database-Test
  #   ports:
  #     - '3307:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}