version: '3.8'
services:
  backend:
    build: .
    container_name: MedShareNetwork-Test
    depends_on:
      - database
    ports:
      - '5000:5000'
    environment:
      - SECRET_KEY=${SECRET_KEY} # Example of passing environment variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  database:
    image: mysql:latest
    container_name: MedShareNetwork-Database-Test
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}